### ISSUE TITLE
Ability to check status of multiple CIDs at once

### ISSUE THREAD

**Issue by lidel** [ipfs/pinning-services-api-spec#1]
Web clients such as ipfs-webui should be able to **check status of multiple CIDs via a single request**, but v0.0.1 does not support that.

### Problem

Apps running in browser contexts have hard limits on how many requests can be executed in specific time window, and that may get even more strict in the future. This means loading status of multiple items may be artificially slowed down by user agent, leading to slugginsh/buggy user interface.

cc @jessicaschilling @rafaelramalho19 from IPFS GUI Team

**Comment by obo20** [comment]
@lidel What's the use case context for this? Are you simply trying to give users a list of their pins based on something like status?

**Comment by lidel** [comment]
@obo20 we may want to add "remote pin status" icon in Files listings in ipfs-webui. That means when user opens a directory via WebUI, we need to check pin status at remote service for every item in that directory (at the current level) to display correct pin status icon.

Instead of asking for each CID status in separate requests, we could either batch them, or ask for pin status using parent directory CID + depth filter  equal 1. 

Statuses would be at least: "pinned", "not pinned" and "pinning in progress" – no standard yet, but we should specify that in the final spec.
