### ISSUE TITLE
Finalizing MVP API Spec for IPFS WebUI integration

### ISSUE THREAD

**Issue by lidel** [ipfs/pinning-services-api-spec#21]
### About

This issue tracks overall finalization status of this spec from the perspective of being ready for stakeholders to start implementation of basic functionality. 

cc @jacobheun @pooja @jessicaschilling 

### Stakeholders

- @jbenet as BDFL
- IPFS Core Impl. WG implementing API client in go-ipfs and js-ipfs
- IPFS GUI Team implementing UI in WebUI / IPFS Desktop app
- Pinning Services implementing the API

### Remaining Issues 

While mostly ready, we need to resolve these issues before API can be fully implemented:

- [x] Clear Milestone issues: https://github.com/ipfs/pinning-services-api-spec/milestone/1
- [ ] (descoped) <del>Additional endpoint for GUI apps that enables user onboarding without copying secrets as noted in https://github.com/ipfs/pinning-services-api-spec/issues/6#issuecomment-656404675 </del>

### Stakeholder Sign-offs

- [x] @jbenet  👉 review scheduled 
- [x] IPFS Cluster / https://github.com/ipfs/notes/issues/378 (@lanzafame)
- [ ] IPFS Core Impl. WG
- [ ] IPFS GUI Team implementing UI in WebUI / IPFS Desktop app
- [ ] IPFS Pinning Services
  - PS list TBD

**Comment by lidel** [comment]
Got approval for general direction from first batch of stakeholders:

📣 **It is ok to start implementing the API, and provide feedback / questions as you go**

FYSA we dont expect groundbreaking changes, but there are some field-specific tweaks/clarifications suggested during internal review, pending community review:
https://github.com/ipfs/pinning-services-api-spec/pulls – PR with filtering by metadata, queued status, removal of unpinned state
https://github.com/ipfs/pinning-services-api-spec/issues/33 – temperature check: should pin object include creation date?

**Comment by pooja** [comment]
I think the pulls link is auto-linking to something broken for some reason. Here is the fresh link: https://github.com/ipfs/pinning-services-api-spec/pulls

**Comment by lidel** [comment]
[v0.0.5](https://github.com/ipfs/pinning-services-api-spec/releases/tag/v0.0.5) was just tagged, addressing feedback from early implementers

**Comment by lidel** [comment]
FYSA we will merge improved Error responses (https://github.com/ipfs/pinning-services-api-spec/pull/59) on Monday and release as `v0.1.0`

**Comment by lidel** [comment]
Basic  integration shipped with ipfs-webui [v2.12.0](https://github.com/ipfs/ipfs-webui/releases/v2.12.0).
It supports remote pining services compatible with a subset of  [v1.0.0](https://github.com/ipfs/pinning-services-api-spec/releases/tag/v1.0.0) of this spec implemented in `pin remote` client that shipped with go-ipfs [v0.8.0](https://github.com/ipfs/go-ipfs/releases/v0.8.0)
