### ISSUE TITLE
Generate API docs

### ISSUE THREAD

**Issue by lidel** [ipfs/pinning-services-api-spec#4]
Needs:
- [ ] API docs generated from `ipfs-pinning-service.yaml` 
  - [ ] in `master`
  - [ ] PRs
- [ ] Link to generated API docs added to README

**Comment by jessicaschilling** [comment]
Also an entry point from docs.ipfs.io 😊

**Comment by GregTheGreek** [comment]
Is there a preferred doc generator? Happy to tackle this.

**Comment by lidel** [comment]
@GregTheGreek afaik there is no preference, the initial draft uses Swagger YAML format, at this stage anything that produces human-readable docs will do. Do you think you could also tackle #3?

**Comment by lidel** [comment]
@GregTheGreek turns out https://mrin9.github.io/RapiDoc/ was super easy to set up as a quick way to get docs for `master` branch:

- https://ipfs.github.io/pinning-services-api-spec/

If you want to add something more advanced to add preview to PRs, PR welcome, but I think its good enough.
