### ISSUE TITLE
Pin.name

### ISSUE THREAD

**Issue by obo20** [ipfs/pinning-services-api-spec#45]
Something we realized early on is that many users wanted a custom "name" associated with their CIDs. While we could have accomplished this by reading through the metadata that users passed to us (and this is something we initially did), users were finding themselves confused by how this behavior worked. Once we switched `name` to being its own custom parameter that was separate from `keyvalues` we started seeing users pass in this attribute with nearly every request. 

Is there interest in possibly adding a `name` parameter that users can pass in with their CIDs?

**Comment by lidel** [comment]
The proposal here is to promote `Pin.meta[name]` to `Pin.name`  AND add `name` filter that returns pin object that include exact match.  

While one can use `Pin.meta[name]` and query via `?meta={name:foo}`, I see how this could improve UX, and introduce more strict standard for petnaming pins.  I'm mildly in favor of this, but would like to hear opinion from @ipfs/wg-pinning-services  and other stakeholders.

Qs:
- Should `name` filter work as exact or partial match?
- What would be the sensible length limit for `Pin.name` string?
  - Should we apply same limit to keys/values in `meta` fields?

**Comment by obo20** [comment]
> Should name filter work as exact or partial match?

Our thought here was to do a partial match since it simply gives the user more flexibility when querying

**Comment by jacobheun** [comment]
This change seems reasonable to me. 

> What would be the sensible length limit for Pin.name string?

Do we have any prior art for the cap here on the pinning services today? Promoting this makes it reasonable to cap, but we should avoid issues with preexisting names.

> Should we apply same limit to keys/values in meta fields?

I think we should avoid this and allow the services to set these. If we prematurely cap these lengths it could create issues if larger max values are later needed.

**Comment by obo20** [comment]
If it helps, our max length for the name is 255 characters

**Comment by andrew** [comment]
@obo20 out of interest, is your partial matching case sensitive?

**Comment by obo20** [comment]
@andrew ours is not

**Comment by lidel** [comment]
@obo20 @andrew  Is this something we should include in the spec, under description of `name` filter?

**Comment by obo20** [comment]
@lidel it's probably best to have an opinion in the spec one way or the other here. Just so behavior is consistent across implementers
