### ISSUE TITLE
Both of the `POST` endpoint docs are outdated

### ISSUE THREAD

**Issue by obo20** [ipfs/pinning-services-api-spec#46]
Both of the `POST` endpoints are outdated. Fixes needed:

Add endpoint:
* the return object is incorrect. I'm assuming this should be the same return object as the modify endpoint?

Modify endpoint: 
* This should only accept a single CID and not an array of CIDs

**Comment by lidel** [comment]
Good catch! Fix in #48, will be released in v0.0.5 by the end of week.
