### ISSUE TITLE
Adjusting limits to match real-life URL length

### ISSUE THREAD

**Issue by lidel** [ipfs/pinning-services-api-spec#53]
@obo20 noted that in theory, v0.0.5 of the spec allows client to pass up to 1k of CIDs as a filter:

> ![2020-08-18--18-58-28](https://user-images.githubusercontent.com/157609/90542788-f0329180-e184-11ea-8a8f-64859304e30d.png)

In practice, each CID will be ~60 characters long, and the real life URL limit in web browsers is around 2000 characters, which means ~30 CIDs being the actual limit in the browser context.

Non-browsers may allow longer URLs, additional research is needed.

**Comment by obo20** [comment]
From my initial research it seems like the major items of relevancy here are:
* The max lengths of all major web browsers are here: https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string

* Web servers may have to do additional configuration to allow for lengths beyond a few thousand. However it should be doable for web servers to accommodate basically any reasonable length of URL (although see possible safety concern below)

* From this comment on the same thread above: https://stackoverflow.com/a/48230425/4822065,  it appears that URL limits can help prevent against DDOS attacks, but I haven't been able to find a lot of information as to how this works with queries / APIs. 

The biggest question I have is: 

What would be the use case for passing in 1000 specific CIDs to this API? I'm can see the obvious use case of asking for the "newest X items" /  "items that match this status" / "items that match this name pattern" / "items that match this metadata", but I'm struggling to think of a specific use case where an application would be querying "give me the items for these 1000 ids".

Right now I would lean towards keeping the API safer to run, but I also don't want to alienate major use cases if there are any that would rely on this functionality. It's also something we can always later add in if needed.

**Comment by lidel** [comment]
I think introducing a query limit of 10 or 25 CIDs is worth considering. 

Rationale:
- Removes performance / platform limitation issues on  the backend
- Should be enough for GUI apps such as webui, where we want to see if file is pinned directly or indirectly by any of parent directories. User probably won't explore directory trees deeper than 10-25, and if they do, then additional request won't hurt much.

**Comment by obo20** [comment]
i would support this change. Even 25 CIDs would keep us under the 8000 character default of NodeJS. 

In many cases, 25 would also fit under the 2Kb limit of internet explorer (although this isn't likely something we need to care about as IE is discontinued).

We would only need to be careful in cases of metadata as we currently don't have a length limit set on these as part of the spec

**Comment by jacobheun** [comment]
As we're already using 10 as a default limit for paging I think it would be good to stick with 10 as the limit here for consistency unless there's a good reason to go beyond that.

**Comment by obo20** [comment]
10 works just fine for me. Are we limiting the overall results returned from this endpoint to 10? Or just the amount of CIDs provided for querying?

**Comment by jacobheun** [comment]
Just the CIDs in the query params, this shouldn't affect the existing results spec.

**Comment by obo20** [comment]
@lidel any thoughts here?

**Comment by lidel** [comment]
@obo20 sounds reasonable, I've opened #62 to change query param limit to `10`
