### ISSUE TITLE
What's the difference between the status `pinning` and `queued`

### ISSUE THREAD

**Issue by 2color** [ipfs/pinning-services-api-spec#94]
The spec mentions that both `queued` and `pending` represent a pending state where the pinning service has yet to fetch the CID from the network. 

Is there an actual difference between the two states? If so, what is it?

**Comment by lidel** [comment]
- `queued` is passive no-op: it adds pin job to the queue but does not consume any resources (yet). 
- `pinning` is active: pinning service is spending resources on in, trying to find providers for all involved CIDs, connect to these providers and download data from them.

@2color does this make sense? 

I'm happy to add something to  [#section/The-pin-lifecycle/Checking-status-of-in-progress-pinning](https://ipfs.github.io/pinning-services-api-spec/#section/The-pin-lifecycle/Checking-status-of-in-progress-pinning) if you propose a PR :)
